name: CI

on:
  push:
    branches:
      - main   # push commit to the main branch
    tags:
      - '*'  # push tag to the main branch
  pull_request:
    branches:
      - main   # pull request to the main branch
  workflow_dispatch:   # allow manual triggering

defaults:
  run:
    shell: bash -l {0}

jobs:
  test-matrix:
    name: CI py${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9
          - "3.10"  # not 3.10 which truncates to 3.1
          - 3.11  # 2022-Q4
      max-parallel: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Python ${{ matrix.python-version }} environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-downloads: true
          cache-env: true
          channel-priority: flexible
          environment-file: .github/env-ci.yml
          environment-name: anaconda-test-env-py-${{ matrix.python-version }}
          extra-specs: |
            python=${{ matrix.python-version }}

      - name: Check Code Style
        run: |
          flake8
          black murky/murky_tool.py
          black murky/create_release_notes.py
          black setup.py

      - name: Python Tests
        run: |
          coverage run --concurrency=thread --parallel-mode -m pytest -vvv .

      - name: Install for functional testing
        run: |
          python3 ./setup.py build sdist
          python3 -m pip install .

      - name: Command Tests
        run: |
          murky_tool --help
          murky_tool name murky/env_example1.yml
          murky_tool conda murky/env_example1.yml
          murky_tool pip murky/env_example1.yml
          murky_create.sh help

      - name: Upload coverage data to coveralls.io
        shell: bash -l {0}
        run: |
          micromamba list coveralls
          which coveralls
          coveralls debug
          coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.test-name }}
          COVERALLS_PARALLEL: true

  # https://coveralls-python.readthedocs.io/en/latest/usage/configuration.html#github-actions-support
  coveralls:
    name: Report unit test coverage to coveralls
    needs: test-matrix
    runs-on: ubuntu-latest
    container: python:3-slim

    steps:
      - name: Gather coverage and report to Coveralls
        run: |
          echo "Finally!"
          pip3 install --upgrade coveralls
          # debug mode: output prepared json and reported files list to stdout
          # https://coveralls-python.readthedocs.io/en/latest/troubleshooting.html
          coveralls debug
          coveralls --service=github --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
