name: CI

on:
  push

defaults:
  run:
    shell: bash -l {0}

jobs:

  part1:
    name: touch
    runs-on: ubuntu-latest

    steps:

      - name: Step 1
        run: |
          ls -lAFgh

      - name: Step 2
        run: |
          touch something

  part2:
    name: waiting
    runs-on: ubuntu-latest
    needs: part1

    steps:

      - name: Step 1
        run: |
          sleep 10
          echo "waited 10s"

      - name: Step 2
        run: |
          echo "no wait"

  part3:
    name: list
    runs-on: ubuntu-latest
    needs: part2

    steps:

      - name: Step 1
        run: |
          ls -lAFgh
